version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: "php packages"
  - package-ecosystem: "github-actions"
    directory: /
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: "github-actions"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
  - package-ecosystem: "docker"
    groups:
      all:
        patterns:
          - "*"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
