version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: daily
    commit-message:
      prefix: "npm"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor","version-update:semver-major",  ]
