import ClientSideScrollRestorer from "@/ClientSideScrollRestorer"
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {FunctionComponent, ReactNode} from "react"

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const RootLayout: FunctionComponent<{
    children:ReactNode
}> = ({children}) => {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ClientSideScrollRestorer/>
        {children}
        </body>
        </html>
    )
}
export default RootLayout
