name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
permissions:
  contents: read
jobs:
  Unit:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [22,24,26]
        nextjs-version: [15,16]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: cd next-app-mock && pnpm i
      - run: pnpm i  && pnpm build
      - run: pnpm add next@^${{ matrix.nextjs-version }}
      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps
      - run: pnpm test
        env:
          CI: true
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: my-artifacts-${{inputs.context}}-${{inputs.job-index}}-${{ matrix.node-version }}-${{ strategy.job-index }}
          path: playwright-report/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: my-artifacts-${{inputs.context}}*
          merge-multiple: true
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Biome
        uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2
        with:
          version: 2.5.10
      - name: Run Biome
        run: biome ci .
  Types:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - run: pnpm tsc
  Test:
    needs: [ Lint, Unit, Types ]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Ready to merge!"
